using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections.Generic;
using System.Linq;
using System;

// シーンをまたいでブロックの状態を保持するための構造体
[Serializable]
public struct BlockState
{
    public string id;              // 対応するブロックのユニークID
    public Vector3 finalPosition; // ブロックが移動し終わった最終位置

    public BlockState(string id, Vector3 finalPosition)
    {
        this.id = id;
        this.finalPosition = finalPosition;
    }
}

public class SceneDataTransfer : MonoBehaviour
{
    // --- シングルトンパターン ---
    private static SceneDataTransfer instance;
    public static SceneDataTransfer Instance
    {
        get
        {
            if (instance == null)
            {
                instance = FindFirstObjectByType<SceneDataTransfer>();
                if (instance == null)
                {
                    GameObject obj = new GameObject("SceneDataTransfer_AutoGenerated");
                    instance = obj.AddComponent<SceneDataTransfer>();
                }
            }
            return instance;
        }
    }

    // ------------------------------------
    // 転送データ
    // ------------------------------------

    [Header("プレイヤーの状態")]
    [HideInInspector] public Vector3 playerPositionToLoad = Vector3.zero;
    [HideInInspector] public int playerDirectionIndexToLoad = 0;

    [Header("ゲーム進行状況と移動回数")]
    public string titleSceneName = "title"; // タイトルシーンの名前
    [HideInInspector] public int lastClearedStageIndex = 0;
    [HideInInspector] public int currentStageMoveCount = 0;
    [HideInInspector] public int movesOnClear = 0;

    [Header("ムーブブロックの状態")]
    [HideInInspector] public List<BlockState> pastBlockStates = new List<BlockState>();

    [Header("アイテムとギミックの状態")]
    [HideInInspector] public bool hasMatchStick = false;
    [HideInInspector] public List<string> burnedObjectIDs = new List<string>();
    [HideInInspector] public List<string> vanishedItemIDs = new List<string>();

    [Header("スイッチと橋の状態")]
    [HideInInspector] public List<string> activatedSwitchIDs = new List<string>();

    [Header("シーン状態")]
    [HideInInspector] public bool isChangingScene = false;
    [HideInInspector] public bool isTalking = false;

    // ----------------------------------------
    // Unityライフサイクル
    // ----------------------------------------

    void Awake()
    {
        Application.targetFrameRate = 60;

        if (instance != null && instance != this)
        {
            Destroy(gameObject);
            return;
        }

        instance = this;
        DontDestroyOnLoad(gameObject);

        // 保存されているクリア状況を読み込む
        lastClearedStageIndex = PlayerPrefs.GetInt("SavedStageIndex", 0);
        Debug.Log($"[SceneDataTransfer] ロード完了。最後にクリアしたステージ: {lastClearedStageIndex}");
    }

    void Update()
    {
        // 常にエスケープキーを監視
        HandleGlobalInput();
    }

    private void HandleGlobalInput()
    {
        // エスケープキーが押されたらタイトルへ戻る
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            // すでに遷移中、または会話中などの場合は制限しても良い（今回は即座に遷移）
            ReturnToTitle();
        }
    }

    // ------------------------------------
    // シーン遷移管理メソッド 
    // ------------------------------------

    public void ReturnToTitle()
    {
        // フェード中なら多重起動を防ぐ
        if (SceneFader.Instance != null && SceneFader.Instance.IsFading) return;

        Debug.Log("[SceneDataTransfer] エスケープキーによりタイトルへ戻ります。");

        // タイトルに戻るときは一時的なステータス（位置や歩数）をリセット
        ClearPlayerState();

        if (SceneFader.Instance != null)
        {
            SceneFader.Instance.LoadSceneWithFade(titleSceneName, FadeColor.Black);
        }
        else
        {
            SceneManager.LoadScene(titleSceneName);
        }
    }

    public void StartSceneChange()
    {
        isChangingScene = true;
        Debug.Log("[SceneDataTransfer] シーン変更処理を開始しました。");
    }

    public void EndSceneChange()
    {
        isChangingScene = false;
        Debug.Log("[SceneDataTransfer] シーン変更処理を完了しました。");
    }

    // ------------------------------------
    // プレイヤーとステージの状態操作
    // ------------------------------------

    public void SavePlayerState(Vector3 pos, int dirIndex)
    {
        playerPositionToLoad = pos;
        playerDirectionIndexToLoad = dirIndex;
    }

    public void IncrementMoveCount()
    {
        currentStageMoveCount++;
        Debug.Log($"[SceneDataTransfer] 移動回数: {currentStageMoveCount}");
    }

    public void RecordStageClear(int clearedStageIndex)
    {
        // 今回のクリア歩数をリザルト表示用に確定させる
        movesOnClear = currentStageMoveCount;

        if (clearedStageIndex > lastClearedStageIndex)
        {
            lastClearedStageIndex = clearedStageIndex;
            PlayerPrefs.SetInt("SavedStageIndex", lastClearedStageIndex);
            PlayerPrefs.Save();
            Debug.Log($"[SceneDataTransfer] ステージ {clearedStageIndex} のクリアを保存しました。");
        }
    }

    // --- ギミック関連のメソッド ---

    public void AcquireMatchStick() => hasMatchStick = true;

    public void RecordBurnedObject(string objectId)
    {
        if (!burnedObjectIDs.Contains(objectId)) burnedObjectIDs.Add(objectId);
    }

    public bool IsObjectBurned(string objectId) => burnedObjectIDs.Contains(objectId);

    public void RecordItemVanished(string itemId)
    {
        if (!vanishedItemIDs.Contains(itemId)) vanishedItemIDs.Add(itemId);
    }

    public bool IsItemVanished(string itemId) => vanishedItemIDs.Contains(itemId);

    public void RecordSwitchActivated(string switchId)
    {
        if (!activatedSwitchIDs.Contains(switchId)) activatedSwitchIDs.Add(switchId);
    }

    public bool IsSwitchActivated(string switchId) => activatedSwitchIDs.Contains(switchId);

    // ------------------------------------
    // リセット処理
    // ------------------------------------

    public void SoftReset()
    {
        playerPositionToLoad = Vector3.zero;
        playerDirectionIndexToLoad = 0;
        pastBlockStates.Clear();
        burnedObjectIDs.Clear();
        vanishedItemIDs.Clear();
        activatedSwitchIDs.Clear();
        hasMatchStick = false;
        isTalking = false;
        Debug.Log("[SceneDataTransfer] ソフトリセット完了。");
    }

    public void ClearPlayerState()
    {
        playerPositionToLoad = Vector3.zero;
        playerDirectionIndexToLoad = 0;
        pastBlockStates.Clear();
        currentStageMoveCount = 0;
        isTalking = false;
        Debug.Log("[SceneDataTransfer] プレイヤーの一時データをリセット。");
    }

    public void FullGameReset()
    {
        ClearPlayerState();
        lastClearedStageIndex = 0;
        PlayerPrefs.DeleteKey("SavedStageIndex");
        hasMatchStick = false;
        burnedObjectIDs.Clear();
        vanishedItemIDs.Clear();
        activatedSwitchIDs.Clear();
        Debug.Log("[SceneDataTransfer] フルゲームリセット実行。");
    }

    // ------------------------------------
    // ブロックデータ処理 
    // ------------------------------------

    public void SaveBlockPositions(List<BlockState> statesToSave)
    {
        pastBlockStates = new List<BlockState>(statesToSave);
    }

    public void AddOrUpdateBlockState(string blockId, Vector3 finalPos)
    {
        int index = pastBlockStates.FindIndex(state => state.id == blockId);
        if (index != -1)
        {
            BlockState updatedState = pastBlockStates[index];
            updatedState.finalPosition = finalPos;
            pastBlockStates[index] = updatedState;
        }
        else
        {
            pastBlockStates.Add(new BlockState(blockId, finalPos));
        }
    }

    public BlockState? GetBlockState(string id)
    {
        BlockState foundState = pastBlockStates.FirstOrDefault(state => state.id == id);
        return pastBlockStates.Any(state => state.id == id) ? foundState : (BlockState?)null;
    }
}